- name: Remove acme.sh internal certificate files and directories (ecc and non-ecc directories if they exist) for domain removal --
  ansible.builtin.include_tasks:
    file: remove-acme-certificate-files-and-directory.yml
    apply:
      tags: remove_selected_certificates
  when:
    - acme_sh_domains and item.domains is defined and item.domains
    - item.remove is defined and item.remove
    - not acme_sh_uninstall or acme_sh_uninstall|bool == false
  loop: "{{ acme_sh_domains }}"
  tags: remove_selected_certificates

- name: Remove acme.sh installed certificate files
  ansible.builtin.include_tasks:
    file: remove-acme-certificate-installed-files-and-directory.yml
    apply:
      tags: remove_selected_certificates
  loop: "{{ acme_sh_domains }}"
  when:
    - acme_sh_domains and item.domains is defined and item.domains
    - item.remove is defined and item.remove
    - not acme_sh_uninstall or acme_sh_uninstall|bool == false
  tags: remove_selected_certificates
