---
- name: Determine if systemd timer file exists
  ansible.builtin.stat:
    path: "{{ systemd_files_location }}/{{ systemd_timer_name }}"
  register: timer_file_exists
  become_user: "{{ acme_sh_become_user }}"
  tags: 
    - systemd_stop_timer

- name: Stop timer if it exists
  ansible.builtin.systemd_service:
    name: "{{ systemd_timer_name }}"
    enabled: false
    state: "stopped"
    daemon_reload: true
  when:
    - timer_file_exists.stat.exists
  become_user: "{{ acme_sh_become_user }}"
  tags:
    - systemd_stop_timer
