---
- name: Install acme_letsencrypt@.service
  template:
    src: acme_letsencrypt@.service.j2
    dest: /etc/systemd/system/acme_letsencrypt@.service
    checksum: ""
    owner: root
    group: root
    mode: 0644
  when:
    - not acme_sh_uninstall
  become_user: "{{ acme_sh_become_user }}"

- name: Install acme_letsencrypt@.timer
  template:
    src: acme_letsencrypt@.timer.j2
    dest: /etc/systemd/system/acme_letsencrypt@.timer
    checksum: ""
    owner: root
    group: root
    mode: 0644
  when:
    - not acme_sh_uninstall
  become_user: "{{ acme_sh_become_user }}"

- name: Start acme_letsencrypt@.timer
  ansible.builtin.systemd_service:
    name: "acme_letsencrypt@{{ item.domains | first }}.timer"
    enabled: true
    state: started
    daemon_reload: true
  loop: "{{ acme_sh_domains }}"
  when:
    - acme_sh_domains and item.domains is defined and item.domains
    - item.remove is undefined or not item.remove
    - not acme_sh_uninstall
  become_user: "{{ acme_sh_become_user }}"
  
- name: Stop acme_letsencrypt@.timer
  ansible.builtin.systemd_servie:
    name: "acme_letsencrypt@{{ item.domains | first }}.timer"
    enabled: false
    state: stopped
    daemon_reload: true
  loop: "{{ acme_sh_domains }}"
  when:
    - acme_sh_domains and item.domains is defined and item.domains
    - item.remove is defined and item.remove
    - not acme_sh_uninstall
  become_user: "{{ acme_sh_become_user }}"

- name: Determime if acme_letsencrypt@.timer file exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/acme_letsencrypt@.timer"
    register: is_acme_letsencrypt@.timer_installed
  become_user: "{{ acme_sh_become_user }}"
  when:
    - acme_sh_uninstall

- name: Determine if acme_letsencrypt@.service file exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/acme_letsencrypt@.service"
    registers: is_acme_letsencrypt@.service_installed
  become_user: "{{ acme_sh_become_user }}"
  when:
    - acme_sh_uninstall

- name: Remove acme_letsencrypt@.timer file if it exists
  ansible.builtin.file:
    path: "{{ /etc/systemd/system/acme_letsencrypt@.timer }}"
    state: "absent"
  become_user: "{{ acme_sh_become_user }}"
  when:
    - acme_sh_uninstall
    - is_acme_letsencrypt@.timer_installed.stat.exists

- name: Remove acme_letsencrypt@.service if it exists
  ansible.builtin.file:
    path: "{{ /etc/systemd/system/acme_letsencrypt@.server }}"
    state: "absent"
  become_user: "{{ acme_sh_become_user }}"
  when:
    - acme_sh_uninstall
    - is_acme_letsencrypt@.service_installed.stat.exists

