---
- name: Determine if systemd timer file exists
  ansible.builtin.stat:
    path: "{{ systemd_files_location }}/{{ systemd_timer_name }}"
  register: timer_exists
  when:
    - not acme_sh_uninstall or acme_sh_uninstall|bool == false
  become_user: "{{ acme_sh_become_user }}"

- name: Determine if systemd service file exists
  ansible.builtin.stat:
    path: "{{ systemd_files_location }}/{{ systemd_service_name }}"
  register: service_exists
  when:
    - not acme_sh_uninstall or acme_sh_uninstall|bool == false
  become_user: "{{ acme_sh_become_user }}"

- name: Start systemd {{ systemd_timer_name }} for domain
  ansible.builtin.systemd_service:
    name: "{{ systemd_timer_name }}"
    enabled: true
    state: "started"
    daemon_reload: true
  when:
    - timer_exists.stat.exists and service_exists.stat.exists
    - not acme_sh_uninstall or acme_sh_uninstall|bool == false
  become_user: "{{ acme_sh_become_user }}"
