---
- name: Determine if systemd timer file exits for domain
  ansible.builtin.stat:
    path: "{{ systemd_files_location }}/acme_letsencrypt@{{ items.domains | first }}.timer"
  register: timer_file_exists
  become_user: "{{ acme_sh_become_user }}"

- name: Determine if systemd service file exits for domain
  ansible.builtin.stat:
    path: "{{ systemd_files_location }}/acme_letsencrypt@{{ items.domains | first }}.service"
  register: service_file_exists
  become_user: "{{ acme_sh_become_user }}"

- name: Remove systemd timer file if if exist for domain
  ansible.builtin.file:
    path: "{{ systemd_files_location }}/acme_letsencrypt@{{ items.domains | first }}.timer"
    state: "absent"
  when:
    - timer_file_exists.stat.exists
  become_user: "{{ acme_sh_become_user }}"

- name: Remove systemd service file if if exist for domain
  ansible.builtin.file:
    path: "{{ systemd_files_location }}/acme_letsencrypt@{{ items.domains | first }}.service"
    state: "absent"
  when:
    - service_file_exists.stat.exists
  become_user: "{{ acme_sh_become_user }}"
